### ISSUE TITLE
web-ext not working after update to 7.1.0

### ISSUE THREAD

**Issue by danbae56** [mozilla/addons#1421]
After successfully building a Firefox add-on using web-ext 6.8.0, I was prompted to update to 7.1.0. After doing so, a long list of warnings about "unsupported engines" was shown by the installer, and when I next tried to build an add-on, or just run `web-ext --version`, I got the following message:

>  % web-ext --version                
> (node:7894) ExperimentalWarning: The ESM module loader is experimental.
> file:///usr/local/lib/node_modules/web-ext/bin/web-ext.js:13<br />
> await webExt.main(absolutePackageDir);<br />
> ^^^^^
> 
> SyntaxError: Unexpected reserved word
>     at Loader.moduleStrategy (internal/modules/esm/translators.js:88:18)
>     at async link (internal/modules/esm/module_job.js:41:21)

What should I do to get web-ext working again?

OS: MacOS 12.4; Terminal asked me to perform an install of Python command-line tools which I did – it was very lengthy but did not change the behaviour of web-ext.

**Comment by danbae56** [comment]
This issue was caused by an old version of node.js. I think it would be helpful if web-ext would suggest a remedy like this (since I guess the problem is rather frequent).
