### ISSUE TITLE
[Bug]: Setting `TESTING_ENV` defined in wrong settings file 

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#15185]
### What happened?

setting `TESTING_ENV` is referenced in a data migration (shipped in [PR](https://github.com/mozilla/addons-server/pull/22818)), but in that environment is undefined leading to the error

```python
Operations to perform:
  Apply all migrations: abuse, access, accounts, activity, addons, admin, akismet, amo, api, applications, auth, bandwagon, blocklist, contenttypes, devhub, discovery, es, files, git, hero, promoted, ratings, reviewers, scanners, search, sessions, shelves, stats, tags, translations, users, versions, waffle, yara, zadmin
Running migrations:
Traceback (most recent call last):
  File "/data/olympia/./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deps/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deps/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/deps/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deps/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/deps/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deps/lib/python3.11/site-packages/django/db/migrations/migration.py", line 127, in apply
    operation.database_forwards(
  File "/deps/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/data/olympia/src/olympia/versions/migrations/0047_auto_20241031_1750.py", line 41, in set_new_builtins
    if settings.TESTING_ENV == False:
       ^^^^^^^^^^^^^^^^^^^^
  File "/deps/lib/python3.11/site-packages/django/conf/__init__.py", line 104, in __getattr__
    val = getattr(_wrapped, name)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'TESTING_ENV'
```

### What did you expect to happen?

- This migration should not fail if the environment variable is not defined, should default to false
- The environment variable should be defined correctly in prod mode.
- Ideally CI should have caught this, but that might be out of scope.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1249)

**Comment by KevinMind** [comment]
Looks like one more robust fix for this class of bug would be to:
- ensure DJANGO_SETTINGS_MODULE is parameterized (right now it is hard coded so we cannot override it in ci if we want)
- add a test to CI that ensures any variables defined in settings.py or settings_test.py are also defined in settings_base.py (not sure how to do that outside of an ast parser)
- alternative we could set the settings module to "dev" settings in CI or define a CI settings?

Our settings are relatively complicated and spread out currently. An additional task could be to try to simplify them a bit

**Comment by KevinMind** [comment]
This also looks like a pretty decent alternative as a built in. Doesn't solve the larger class of bugs but makes this one easier https://docs.pytest.org/en/stable/reference/reference.html#envvar-PYTEST_VERSION

**Comment by ioanarusiczki** [comment]
Looks like a qa not needed
