### ISSUE TITLE
[Bug]: TypeError while running `/manage.py fetch_prod_addons` locally

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#15194]
### What happened?

I ran `./manage.py fetch_prod_addons` and after a few add-ons imported, I got this error:

```
Traceback (most recent call last):
  File "/data/olympia/./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/olympia/src/olympia/landfill/management/commands/fetch_prod_addons.py", line 50, in handle
    self.fetch_addon_data(options)
  File "/data/olympia/src/olympia/landfill/management/commands/fetch_prod_addons.py", line 174, in fetch_addon_data
    self._get_addons_from_page(page, params)
  File "/data/olympia/src/olympia/landfill/management/commands/fetch_prod_addons.py", line 66, in _get_addons_from_page
    self._handle_addon(addon)
  File "/data/olympia/src/olympia/landfill/management/commands/fetch_prod_addons.py", line 116, in _handle_addon
    category = addon_data['categories']['firefox'][0]
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

### What did you expect to happen?

No error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1258)

**Comment by diox** [comment]
Yeah that command is a hack that we are not properly maintaining... That breakage was caused by https://github.com/mozilla/addons/issues/4579 - the v5 API it's using no longer returns categories per application.
