### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by netquik** [mozilla/addons#303]
[CnCTA SoO SCRIPT PACK - FIREFOX.zip](https://github.com/mozilla/addons/files/674837/CnCTA.SoO.SCRIPT.PACK.-.FIREFOX.zip)

The error occurred during the submission of a new add-on

The add-on is unlisted

https://addons.mozilla.org/it/developers/addon/submit/upload-unlisted

Current local time: 	2:05:26 am
Date: 	Wednesday 28 December 2016
Time zone: 	CET (Central Europe Time)
Current time zone offset: 	 +01:00 hours

https://addons.mozilla.org/it/developers/upload/a35ffa7c833d49609f4248d1af3c3059

**Comment by netquik** [comment]
Actually i installed the extension temporary as a file zip and it seems to work as expected

**Comment by netquik** [comment]
Is there a way to know exactly why it fails?
unexpected error is not useful to understand
Thanks

**Comment by andymckay** [comment]
I got this error on the latest checkout of add-ons linter:

```
  tmp $ ~/sandboxes/addons-linter/bin/addons-linter CnCTA.SoO.SCRIPT.PACK.-.FIREFOX.zip --stack
TypeError: Cannot read property 'init' of undefined
    at /Users/andy/sandboxes/addons-linter/dist/webpack:/src/utils.js:125:16
    at Array.forEach (native)
    at getVariable (/Users/andy/sandboxes/addons-linter/dist/webpack:/src/utils.js:123:13)
    at EventEmitter.CallExpression (/Users/andy/sandboxes/addons-linter/dist/webpack:/src/rules/javascript/eval_string_arg.js:16:29)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/andy/sandboxes/addons-linter/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/andy/sandboxes/addons-linter/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/andy/sandboxes/addons-linter/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/andy/sandboxes/addons-linter/node_modules/eslint/lib/eslint.js:898:36)
```

Not sure what that is yet. Summoning @tofumatt for some ideas.

**Comment by tofumatt** [comment]
Looks like this is a change in the output from eslint/esprima that we didn't catch because our tests mock the output 😢

Quick fix should be downgrading those dependencies as we don't need their new features as far as I know.
